##data source constants
#spring.datasource.url=jdbc:mysql://localhost:3306/auth
#spring.datasource.username=root
#spring.datasource.password=123456
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.schema=classpath:/db/init.db
#spring.datasource.data=classpath:/db/data.db
##spring.datasource.driverClassName=com.mysql.jdbc.Driver
#
## JPA constants
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.database=MYSQL
#spring.jpa.openInView=false
#spring.jpa.show_sql=true
#spring.jpa.generate-ddl=false
#spring.jpa.hibernate.ddl-auto=none
#
##web server
#server.port=9191
#server.servlet.context-path=/api
#
##Application specific
#authentication.oauth.clientId=account-app
#authentication.oauth.secret=secret
#authentication.oauth.tokenValidityInSeconds=1800
## mysql above

spring:
  datasource:
    url: jdbc:h2:mem:spring_boot_oauth2;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath:db/init.sql
    data: classpath:db/data.sql
    dbcp2:
      validation-query: SELECT * from user
  # JPA constants
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    open-in-view: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
  # h2 constants
  h2:
    console:
      path: /h2
      settings:
        web-allow-others: true
      enabled: true
  thymeleaf:
    prefix: classpath:/resources/

#spring.datasource.driverClassName=com.mysql.jdbc.Driver


#web server
server:
  port: 9002
  servlet:
    context-path: /api

#Application specific
authentication:
  oauth:
    clientid: auth
    secret: secret
    tokenValidityInSeconds: 1800
    ignoreUrls: /register,/h2,/activate,/hello/**,/api/validate/image,/logins.html,/provider.html,/api/validate/provider,/api/authentication/provider
auth:
  security:
    browser:
      login-page: /demo-login.html
      login-type: JSON
      redirect-url: /index.html
      remember-me-seconds: 3600
      session:
        max-age: 3600
        redirect-url: /session-invalidate.html
        max-sessions: 100
    code:
      image:
        length: 4
        width: 30
        height: 60
        font-size: 24
        expire-in: 60
        miss: 5
        url: /api/code/image
      sms:
        length: 6
        expire-in: 300
        url: /api/code/sms
    social:
      qq:
        app-id:
        app-secret:
logging:
  level:
    root: INFO
    org:
      hibernate: INFO
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
            BasicExtractor: TRACE
