server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/client
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  http:
    converters:
      preferred-json-mapper: jackson
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html